<a href="https://colab.research.google.com/github/wahiwatkar06-gif/mdm-practicals/blob/main/Practical5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import required libraries
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import plot_tree

In [ ]:
data = pd.read_csv("/content/wireless_signal_quality_dataset (2).csv")
print("First five records:")
print(data.head())
print("\nDataset Shape:")
print(data.shape)

First five records:
   Signal_Strength_dBm  SNR_dB  Interference_dB  Distance_m  Frequency_GHz  \
0                  -41       6                0         257            5.0   
1                  -86      25               20         134            2.4   
2                  -73      27                0         385            2.4   
3                  -57       5                0         255            5.0   
4                  -87      15               24          61            5.0   

   Channel_Bandwidth_MHz  Noise_Floor_dBm  Connected_Devices  \
0                    160             -100                 24   
1                    160              -96                 41   
2                     20              -72                 13   
3                    160              -86                  9   
4                     20              -79                 32   

   Estimated_Throughput_Mbps Quality  
0                         18    Poor  
1                         55    Poor  
2        


Dataset Shape


In [ ]:
#Separate features  and target
x=data.drop('Quality',axis=1)
y=data['Quality']

encoder = LabelEncoder()
y=encoder.fit_transform(y)

print("\nClasses Labels:")
print(encoder.classes_)


Classes Labels:
['Excellent' 'Fair' 'Good' 'Poor']


In [ ]:
#Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

In [ ]:
#Build random forest model
rf = RandomForestClassifier(
    n_estimators=100,
    criterion='gini',
    random_state=42
)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
#Prediction
y_pred = rf.predict(X_test)

In [ ]:
#Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy = {:.2f}%".format(accuracy*100))


Accuracy = 88.00%


In [ ]:
#Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred,target_names=encoder.classes_))


Classification Report:
              precision    recall  f1-score   support

   Excellent       0.00      0.00      0.00         1
        Fair       0.75      1.00      0.86         9
        Good       0.00      0.00      0.00         2
        Poor       1.00      1.00      1.00        13

    accuracy                           0.88        25
   macro avg       0.44      0.50      0.46        25
weighted avg       0.79      0.88      0.83        25



/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
#confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)


Confusion Matrix:
[[ 0  1  0  0]
 [ 0  9  0  0]
 [ 0  2  0  0]
 [ 0  0  0 13]]


In [ ]:
#Feature importance
importances = pd.Series(
    rf.feature_importances_,
    index=x.columns
)
importances = importances.sort_values(ascending=False)
print("\nFeature Importance:")
print(importances)


Feature Importance:
Signal_Strength_dBm          0.360444
SNR_dB                       0.207060
Estimated_Throughput_Mbps    0.150236
Interference_dB              0.079427
Distance_m                   0.060098
Noise_Floor_dBm              0.048804
Connected_Devices            0.047951
Channel_Bandwidth_MHz        0.028872
Frequency_GHz                0.017107
dtype: float64
